check json format as well

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,20 +31,33 @@ jobs:
       run: |
         if [ "${{ github.event_name }}" == "pull_request" ]; then
           base_sha=$(git rev-parse ${{ github.event.pull_request.base.sha }})
-          echo "files=$(git diff --name-only $base_sha HEAD | grep '\.cs$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
+          echo "cs_files=$(git diff --name-only $base_sha HEAD | grep '\.cs$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
+          echo "json_files=$(git diff --name-only $base_sha HEAD | grep '\.json$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
         else
-          echo "files=$(git diff --name-only HEAD^ HEAD | grep '\.cs$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
+          echo "cs_files=$(git diff --name-only HEAD^ HEAD | grep '\.cs$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
+          echo "json_files=$(git diff --name-only HEAD^ HEAD | grep '\.json$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
         fi
 
-    - name: Check format of changed files
-      if: steps.changed-files.outputs.files != ''
+    - name: Check format of changed C# files
+      if: steps.changed-files.outputs.cs_files != ''
       run: |
-        changed_files="${{ steps.changed-files.outputs.files }}"
+        changed_files="${{ steps.changed-files.outputs.cs_files }}"
         for file in $changed_files; do
-          if [[ $file == *.cs ]]; then
-            dotnet format --no-restore --verify-no-changes --verbosity detailed --include $file
+          dotnet format --no-restore --verify-no-changes --verbosity detailed --include $file
+        done
+
+    - name: Check format of changed JSON files
+      if: steps.changed-files.outputs.json_files != ''
+      run: |
+        npm install -g jsonlint
+        changed_files="${{ steps.changed-files.outputs.json_files }}"
+        for file in $changed_files; do
+          if ! jsonlint -q $file; then
+            echo "Error: $file is not properly formatted JSON."
+            exit 1
           fi
         done
+
     - name: Build Neo.Compiler.CSharp
       run: dotnet build ./src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
     - name: Build Neo.SmartContract.Template and test templates
